embed_assets: on

javascripts:
  base:
    - public/javascripts/jquery.TextAreaExpander.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/jquery-ui-timepicker-addon.js
    - public/javascripts/jquery.fancybox-1.3.4.js
    - public/javascripts/jquery.focuslost.js
    - public/javascripts/jwplayer.js
    - public/javascripts/application.js
    - public/javascripts/locales.js
    - public/javascripts/widgets.js
    - public/javascripts/jquery.typing-0.2.0.min.js
    - public/javascripts/jquery.fileupload.js
    - public/javascripts/jquery.iframe-transport.js
    - public/javascripts/jquery.tmpl.min.js
    - public/javascripts/jquery.jplayer.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.Jcrop.min.js
    - public/javascripts/jquery.autoSuggest.js
    - public/javascripts/jquery.jcarousel.js
    - public/javascripts/jquery.rangyinputs.js
    - public/javascripts/jquery.mousewheel-3.0.4.pack.js
    - public/javascripts/jquery.jscrollpane.js
    - public/javascripts/jquery.ba-bbq.js
    - public/javascripts/jquery.endless-scroll.js
    - public/javascripts/jquery.timeago.js
    - public/javascripts/client/application.js
    - public/javascripts/client/util/*.js
    - public/javascripts/events.widgets.js
    - public/javascripts/home.widgets.js
    - public/javascripts/profile.widgets.js
    - public/javascripts/login.widgets.js
    - public/javascripts/settings.widgets.js
    - public/javascripts/iphone-style-checkboxes.js
    - public/javascripts/jquery.clickout.js
    - public/javascripts/itmsCheck.js
    - public/javascripts/jquery.tools.min.js
    - public/javascripts/jquery.cycle.all.js
    - public/javascripts/jquery.blockUI.js
    - public/javascripts/SPLASH.Widgets.pulsars.js
    - public/javascripts/SPLASH.Widgets.sticky.js
    - public/javascripts/SPLASH.Widgets.homepage.js
    - public/javascripts/SPLASH.Widgets.waterNums.js
    - public/javascripts/SPLASH.Widgets.numFlipper.js
    - public/javascripts/SPLASH.Widgets.JPlayerSeekable.js
    - public/javascripts/client/**/*.js

stylesheets:
  base:
    - public/stylesheets/vendor/yui-reset.css
    - public/stylesheets/vendor/yui-base.css
    - public/stylesheets/vendor/yui-fonts.css
    - public/stylesheets/vendor/yui-grids.css
    - public/stylesheets/vendor/jquery.fancybox-1.3.4.css
    - public/stylesheets/navigation.css
    - public/stylesheets/inline_labels.css
    - public/stylesheets/vendor/formtastic.css
    - public/stylesheets/vendor/formtastic_changes.css
    - public/stylesheets/flash_messages.css
    - public/stylesheets/jquery.Jcrop.css
    - public/stylesheets/jquery.jscrollpane.css
    - public/css/fonts.css
