embed_assets: on

javascripts:
  base:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery-ui-1.8.5.custom.min.js
    - public/javascripts/jquery-ui-timepicker-addon.js
    - public/javascripts/jquery.fancybox-1.3.4.js
    - public/javascripts/jwplayer.js
    - public/javascripts/application.js

  soundcloud:
    - public/javascripts/soundcloud.min.js

stylesheets:
  base:
    - public/stylesheets/vendor/yui-reset.css
    - public/stylesheets/vendor/yui-base.css
    - public/stylesheets/vendor/yui-fonts.css
    - public/stylesheets/vendor/yui-grids.css
    - public/stylesheets/core.css
    - public/stylesheets/vendor/jquery.fancybox-1.3.4.css
    - public/stylesheets/vendor/ui-lightness/jquery-ui-1.8.5.custom.css
    - public/stylesheets/navigation.css
    - public/stylesheets/inline_labels.css
    - public/stylesheets/vendor/formtastic.css
    - public/stylesheets/vendor/formtastic_changes.css
    - public/stylesheets/flash_messages.css
    - public/stylesheets/style.css
