embed_assets: on

javascripts:
  base:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/jquery-ui-timepicker-addon.js
    - public/javascripts/jquery.fancybox-1.3.4.js
    - public/javascripts/jwplayer.js
    - public/javascripts/application.js
    - public/javascripts/locales.js
    - public/javascripts/widgets.js
    - public/javascripts/jquery.typing-0.2.0.min.js
    - public/javascripts/routes.js
    - public/javascripts/searchbox.js
    - public/javascripts/jquery.fileupload.js
    - public/javascripts/jquery.iframe-transport.js
    - public/javascripts/jquery.tmpl.min.js
    - public/javascripts/jquery.jplayer.min.js
    - public/javascripts/jquery.jeditable.js
    - public/javascripts/jquery.Jcrop.min.js
    - public/javascripts/jquery.autoSuggest.js
    - public/javascripts/jquery.jcarousel.js
    - public/javascripts/jquery.rangyinputs.js
    - public/javascripts/jquery.ba-bbq.js
    - public/javascripts/jquery.endless-scroll.js
    - public/javascripts/json2.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/models.js
    - public/javascripts/search.widgets.js
    - public/javascripts/home.widgets.js

  pjax:
    - public/javascripts/jquery.pjax.js
    - public/javascripts/pjax.widgets.js

stylesheets:
  base:
    - public/stylesheets/vendor/yui-reset.css
    #- public/stylesheets/demoStyles.css
    - public/stylesheets/vendor/yui-base.css
    - public/stylesheets/vendor/yui-fonts.css
    - public/stylesheets/vendor/yui-grids.css
    # - public/stylesheets/core.css
    - public/stylesheets/vendor/jquery.fancybox-1.3.4.css
    - public/stylesheets/navigation.css
    - public/stylesheets/inline_labels.css
    - public/stylesheets/vendor/formtastic.css
    - public/stylesheets/vendor/formtastic_changes.css
    - public/stylesheets/flash_messages.css
    # - public/stylesheets/style.css
    # - public/stylesheets/header.css
    - public/stylesheets/widgets.css
    - public/stylesheets/vendor/jplayer.blue.monday.css
    - public/stylesheets/jquery.Jcrop.css
    - public/stylesheets/vendor/autoSuggest.css
    - public/css/style.css
    - public/css/fonts.css
    - public/stylesheets/style-overrides.css
